### ISSUE TITLE
Use official repos

### ISSUE THREAD

**Issue by Caesar2011** [syumai/dejs#41]
Could you please link to the official repository instead of your copied version in vendor? Then the deno cache for overlapping files could be used, its more up-to-date and it is even more trustworthy.

Add external dependencies to `deps.ts` and reference them from there within your local project. It makes it more clear which dependencies you use.

**Comment by syumai** [comment]
`vendor` is not directory of copies. These files are just a alias like below.

```ts
export * from 'https://deno.land/std@v0.42.0/io/bufio.ts';
```

These dependencies are managed by [dem](https://github.com/syumai/dem). This tool makes easier to update dependencies.

**Comment by syumai** [comment]
@Caesar2011 I've added descriptions to README.md.
https://github.com/syumai/dejs/pull/46

If this is not enough, please reopen this issue.
