### ISSUE TITLE
DOUBT: dynamic render

### ISSUE THREAD

**Issue by cindRoberta** [syumai/dejs#42]
Hi, I would like to know if there is a way to render dynamically on client side, I used abc as in the example: https://deno.land/x/abc/examples/template/

but I can't to use event handlers like onclick

```js
// index.ejs
<%
  let color= "blue";
  function changeColor() { color= "green"; }
 %>
```
```html
<button onclick=<%= changeColor() %>>Change p color</button>
<p style="color: <%= color %>"></p>
```

I know use Vanilla, I could have used document.getElementById("aaa").style.color= "yellow"; in a <script>, the question is about change variables dynamically on browsers. Because if not dynamic, I see no reason to use static ejs

thanks

**Comment by syumai** [comment]
EJS provides a way to render a static string.
Event-driven rendering is not supported. It must be implemented on the client side.
Because it's a browser's feature.
Please consider using `<script>` tag for dynamic rendering.

If this is not enough as answer, please reopen this issue.
