### ISSUE TITLE
I suggest to refuse to use `eval `

### ISSUE THREAD

**Issue by irustm** [syumai/dejs#44]
https://github.com/syumai/dejs/blob/master/mod.ts#L58

It affects performance, and safety.

It's not used in the original.

https://github.com/mde/ejs/blob/master/lib/ejs.js

**Comment by syumai** [comment]
@irustm Thank you for giving me this suggestion.
After some researches, I decided to use `Function` instead of `eval`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function
Thanks!
