### ISSUE TITLE
Include not working dejs

### ISSUE THREAD

**Issue by devYusuf** [syumai/dejs#54]
Hello, guys I'm having problem in including ejs file

 I included my controller 
```
import { viewPath } from "../globe.ts";
import { renderFile } from "https://deno.land/x/dejs/mod.ts";
const { copy, stdout } = Deno;
const home = async () => {
  let home = await renderFile(`${viewPath}/home.ejs`, { vp: viewPath });
  //return await copy(home, stdout);
};

export { home };

```
in my app entry point

```
import { app, get, post } from "https://denopkg.com/syumai/dinatra/mod.ts";
import { home } from "./controllers/app.controllers.ts";

app(
  get("/", async () => await home()),
);
```
in my home.ejs
```
<%- await include(`partials/head.ejs`, {}); %>
```
the result in browser just returned `Internal server error`

**Comment by syumai** [comment]
@devYusuf I couldn't find `"../globe.ts";`.
Would you give me that file or URL of repository?

**Comment by devYusuf** [comment]
@syumai here's the code in it.
```
const { cwd } = Deno;

export const viewPath = `${cwd()}/views`;

```

**Comment by syumai** [comment]
@devYusuf I've fixed these bugs and released dejs@0.7.0.
Thank you for reporting this issue!

**Comment by devYusuf** [comment]
@syumai the app continue dying. localhost refused to connect.
```
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async open ($deno$/files.ts:37:15)
    at async renderFileToString (mod.ts:190:16)
    at async renderFile (mod.ts:205:18)
    at async include (mod.ts:35:18)
    at async eval (eval at <anonymous> (https://raw.githubusercontent.com/syumai/dejs/0.7.0/mod.ts:59:58), <anonymous>:4:44)
```

**Comment by syumai** [comment]
@devYusuf It seems other problem not related to dejs.
This code is working.

```ts
import { viewPath } from '../globe.ts';
import { renderFile } from 'https://deno.land/x/dejs@0.7.0/mod.ts';
const { copy, stdout } = Deno;
const home = async () => {
  let home = await renderFile(`${viewPath}/home.ejs`, { vp: viewPath });
  return home;
};

export { home };
```

**Comment by syumai** [comment]
Replace your code with my example or try `deno run --reload` option.

**Comment by devYusuf** [comment]
Okay thanks @syumai

**Comment by devYusuf** [comment]
I run it now and still getting the result!

**Comment by syumai** [comment]
@devYusuf Would you upload repo to GitHub? There is too little information to consider about the problem.
Maybe the file paths of views are wrong.

**Comment by devYusuf** [comment]
@syumai this is it at [https://github.com/devYusuf/denostack](https://github.com/devYusuf/denostack)

**Comment by syumai** [comment]
@devYusuf 
Please use `<%- await include(`views/partials/head.ejs`, {}); %>` in views/home.ejs.
include's paths are not relative from view file. It's relative from project root.

**Comment by devYusuf** [comment]
@syumai  much thanks, It's now working well.
can I contribute to this project?

**Comment by syumai** [comment]
PRs are welcome. This package does not support most ejs features.

**Comment by syumai** [comment]
This issue seems to be resolved. I close this issue.
