### ISSUE TITLE
https://deno.land/x/dejs@0.9.0/mod.ts 404

### ISSUE THREAD

**Issue by binggg** [syumai/dejs#65]
curl https://deno.land/x/dejs@0.9.0/mod.ts -I 
HTTP/1.1 200 Connection Established

HTTP/2 404 
date: Thu, 12 Nov 2020 12:47:28 GMT
content-type: text/plain;charset=UTF-8
content-length: 13
set-cookie: __cfduid=dd5fa0a41d6ea41b07d88851a78602d8d1605185247; expires=Sat, 12-Dec-20 12:47:27 GMT; path=/; domain=.deno.land; HttpOnly; SameSite=Lax; Secure
access-control-allow-origin: *
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=CGm%2Bko%2FdQmFJH06j5rLewlgaWoGUjj7Xm%2Fj9Xtdq1yMNDgY0CEOeMnV5jvOFDFepbUbSBwiaQV%2F7aYWqfWoAi%2BViK6MmWZSMTmY%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 5f105c958de20ac0-NRT

**Comment by Tcheikovski** [comment]
Same problem here. You still can import the module from github:

https://raw.githubusercontent.com/syumai/dejs/0.9.0/mod.ts

**Comment by syumai** [comment]
I don't know why, but it definitely looks removed.
As a workaround, I would like to publish 0.9.1.
https://github.com/syumai/dejs/releases

**Comment by dontlaugh** [comment]
Still a problem for me w/ 0.9.1 and 0.9.2

I will use github import int he meantime

**Comment by syumai** [comment]
@binggg @Tcheikovski @dontlaugh 
This issue was solved on `0.9.3`. I'm sorry for the inconvinience.
https://deno.land/x/dejs@0.9.3
